import { createHash } from "node:crypto";
import type { ReportModel } from "./contracts";
import { buildPresentationOutline } from "./presentation";

export type RenderedReportPdf = {
  bytes: Uint8Array;
  contentHash: string;
  pageCount: number;
};

/**
 * FIN-002 PDF renderer — presentation upgrade only.
 * Uses the shared presentation outline so PDF narrative matches in-app preview.
 * Does not change ReportingService, calculations, or vault behavior.
 */
export function renderReportPdf(model: ReportModel): RenderedReportPdf {
  const pages = paginate(buildPresentationOutline(model), 42);
  const bytes = buildMultiPagePdf(pages, model);
  return {
    bytes,
    contentHash: createHash("sha256").update(bytes).digest("hex"),
    pageCount: pages.length
  };
}

type PdfPage = string[];

function paginate(lines: string[], maxLinesPerPage: number): PdfPage[] {
  const pages: PdfPage[] = [];
  // Prefer breaks near blank lines to reduce widows/orphans.
  let buffer: string[] = [];
  for (let i = 0; i < lines.length; i += 1) {
    buffer.push(lines[i] ?? "");
    const atLimit = buffer.length >= maxLinesPerPage;
    const naturalBreak = (lines[i] ?? "") === "" && buffer.length >= maxLinesPerPage - 8;
    if (atLimit || naturalBreak) {
      // Keep last non-empty section header with following content when possible
      if (atLimit && buffer.length > 4 && (buffer[buffer.length - 1] ?? "") !== "") {
        const spill = buffer.splice(buffer.length - 2, 2);
        pages.push(buffer);
        buffer = spill;
      } else {
        pages.push(buffer);
        buffer = [];
      }
    }
  }
  if (buffer.length > 0) pages.push(buffer);
  return pages.length > 0 ? pages : [[""]];
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildMultiPagePdf(pages: PdfPage[], model: ReportModel): Uint8Array {
  const pageCount = pages.length;
  const kids: string[] = [];
  for (let i = 0; i < pageCount; i += 1) {
    kids.push(`${3 + i * 2} 0 R`);
  }
  const fontObj = 3 + pageCount * 2;
  const boldFontObj = fontObj + 1;

  const assembled: string[] = [];
  assembled.push("1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj");
  assembled.push(`2 0 obj<< /Type /Pages /Kids [${kids.join(" ")}] /Count ${pageCount} >>endobj`);

  for (let i = 0; i < pageCount; i += 1) {
    const pageObj = 3 + i * 2;
    const contentObj = pageObj + 1;
    const contentLines = pages[i] ?? [];
    const header = `${model.identity.organizationName} · ${model.identity.reportTitle}`;
    const footer = `Prepared by ${model.identity.managerName}  ·  Generated by M.P.A.  ·  Confidential  ·  Page ${i + 1} of ${pageCount}`;

    const streamParts = [
      "BT",
      `/F2 8 Tf`,
      "48 764 Td",
      "11 TL",
      `(${escapePdfText(truncate(header, 90))}) Tj`,
      "T*",
      "T*",
      `/F1 9 Tf`,
      ...contentLines.flatMap((line) => {
        const isHeading =
          line.startsWith("EXECUTIVE") ||
          line.startsWith("VISUAL") ||
          line.startsWith("REPORT HEALTH") ||
          line.startsWith("TOTALS") ||
          line.startsWith("NOTES") ||
          line.startsWith("FINANCIAL") ||
          line.startsWith(">") ||
          line.startsWith("---");
        const font = isHeading ? "/F2 10 Tf" : "/F1 9 Tf";
        return [font, `(${escapePdfText(line)}) Tj`, "T*"];
      }),
      "ET",
      "BT",
      "/F1 8 Tf",
      "48 36 Td",
      `(${escapePdfText(truncate(footer, 100))}) Tj`,
      "ET"
    ];
    const stream = streamParts.join("\n");
    assembled.push(
      `${pageObj} 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${contentObj} 0 R /Resources<< /Font<< /F1 ${fontObj} 0 R /F2 ${boldFontObj} 0 R >> >> >>endobj`
    );
    assembled.push(`${contentObj} 0 obj<< /Length ${stream.length} >>stream\n${stream}\nendstream endobj`);
  }

  assembled.push(`${fontObj} 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj`);
  assembled.push(`${boldFontObj} 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>endobj`);

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of assembled) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${obj}\n`;
  }
  const xrefPos = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${assembled.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= assembled.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${assembled.length + 1} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}

function truncate(value: string, max: number): string {
  return value.length <= max ? value : `${value.slice(0, max - 1)}…`;
}
