import { describe, expect, it } from "vitest";
import { buildPeriod, buildReportModel } from "./engine";
import {
  buildExecutiveKpis,
  buildPresentationCharts,
  buildPresentationOutline,
  reportHasActivity
} from "./presentation";
import { renderReportPdf } from "./pdf-renderer";
import type { ReportingSnapshot } from "./read-sources";
import type { PropertyRecord } from "../property/contracts";

function snapshot(): ReportingSnapshot {
  const property: PropertyRecord = {
    id: "11111111-1111-1111-1111-111111111111",
    organizationId: "22222222-2222-2222-2222-222222222222",
    name: "Cedar Court",
    code: "CC",
    propertyType: "multi_family",
    status: "active",
    description: null,
    addressLine1: "100 Main St",
    addressLine2: null,
    city: "Austin",
    stateRegion: "TX",
    postalCode: "78701",
    countryCode: "US",
    timezone: "America/Chicago",
    latitude: null,
    longitude: null,
    ownershipEntityName: null,
    ownerContactName: null,
    ownerContactEmail: null,
    ownerContactPhone: null,
    coverImageUrl: null,
    metadata: {},
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    archivedAt: null,
    deletedAt: null
  };
  return {
    organizationName: "Demo PM Co",
    property,
    managerName: "Alex Manager",
    charges: [],
    payments: [
      {
        id: "p1",
        organizationId: property.organizationId,
        paymentNumber: "PAY-1",
        rentChargeId: null,
        leaseId: null,
        propertyId: property.id,
        unitId: null,
        tenantId: null,
        amount: 1200,
        paymentMethod: "ach",
        paymentDate: "2026-07-05",
        status: "completed",
        referenceNote: null,
        metadata: {},
        createdAt: "2026-07-05T00:00:00.000Z",
        updatedAt: "2026-07-05T00:00:00.000Z",
        archivedAt: null,
        deletedAt: null
      }
    ],
    expenses: [
      {
        id: "e1",
        organizationId: property.organizationId,
        expenseNumber: "EXP-1",
        propertyId: property.id,
        vendorId: null,
        workOrderId: null,
        category: "maintenance",
        customCategory: null,
        description: "HVAC repair",
        amount: 200,
        expenseDate: "2026-07-10",
        status: "paid",
        vendorBillPlaceholder: null,
        metadata: {},
        createdAt: "2026-07-10T00:00:00.000Z",
        updatedAt: "2026-07-10T00:00:00.000Z",
        archivedAt: null,
        deletedAt: null
      }
    ],
    units: [],
    leases: [],
    workOrders: [],
    awaitingReconciliationCount: 0,
    periodCharges: [],
    periodPayments: [],
    periodExpenses: [],
    periodWorkOrders: [],
    recognitionBasis: "cash"
  };
}

describe("FIN-002 presentation", () => {
  it("builds executive KPIs and charts without changing totals", () => {
    const period = buildPeriod(2026, 7);
    const model = buildReportModel(
      "monthly_profit_and_loss",
      {
        ...snapshot(),
        periodPayments: snapshot().payments,
        periodExpenses: snapshot().expenses
      },
      period
    );
    const kpis = buildExecutiveKpis(model);
    expect(kpis.map((kpi) => kpi.label)).toEqual(["Income", "Expenses", "Net Income"]);
    expect(kpis.find((kpi) => kpi.label === "Net Income")?.value).toContain("1,000");
    const charts = buildPresentationCharts(model);
    expect(charts[0]?.title).toBe("Income vs Expenses");
    expect(reportHasActivity(model)).toBe(true);
  });

  it("shares outline content between presentation and PDF", () => {
    const period = buildPeriod(2026, 7);
    const model = buildReportModel("owner_statement", snapshot(), period);
    const outline = buildPresentationOutline(model);
    expect(outline.some((line) => line.includes("EXECUTIVE SUMMARY"))).toBe(true);
    expect(outline.some((line) => line.includes("FINANCIAL INSIGHTS"))).toBe(true);
    expect(outline.some((line) => line.includes("Generated by M.P.A."))).toBe(true);
    const pdf = renderReportPdf(model);
    expect(Buffer.from(pdf.bytes.slice(0, 4)).toString("utf8")).toBe("%PDF");
    expect(pdf.pageCount).toBeGreaterThanOrEqual(1);
  });
});
