import { serverEnvSchema } from "@mpa/shared";

export const serverEnv = serverEnvSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env["NEXT_PUBLIC_APP_NAME"],
  NEXT_PUBLIC_APP_URL: process.env["NEXT_PUBLIC_APP_URL"],
  NEXT_PUBLIC_SUPABASE_URL: process.env["NEXT_PUBLIC_SUPABASE_URL"],
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env["NEXT_PUBLIC_SUPABASE_ANON_KEY"],
  SESSION_COOKIE_NAME: process.env["SESSION_COOKIE_NAME"],
  SUPABASE_SERVICE_ROLE_KEY: process.env["SUPABASE_SERVICE_ROLE_KEY"],
  STRIPE_SECRET_KEY: process.env["STRIPE_SECRET_KEY"],
  STRIPE_WEBHOOK_SECRET: process.env["STRIPE_WEBHOOK_SECRET"],
  STRIPE_SAAS_WEBHOOK_SECRET: process.env["STRIPE_SAAS_WEBHOOK_SECRET"],
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
  STRIPE_PRICE_PM_PROFESSIONAL_MONTHLY: process.env["STRIPE_PRICE_PM_PROFESSIONAL_MONTHLY"],
  STRIPE_PRICE_PM_PROFESSIONAL_ANNUAL: process.env["STRIPE_PRICE_PM_PROFESSIONAL_ANNUAL"],
  STRIPE_PRICE_PM_BUSINESS_MONTHLY: process.env["STRIPE_PRICE_PM_BUSINESS_MONTHLY"],
  STRIPE_PRICE_PM_BUSINESS_ANNUAL: process.env["STRIPE_PRICE_PM_BUSINESS_ANNUAL"],
  STRIPE_SAAS_AUTOMATIC_TAX: process.env["STRIPE_SAAS_AUTOMATIC_TAX"],
  RESEND_API_KEY: process.env["RESEND_API_KEY"],
  RESEND_FROM_EMAIL: process.env["RESEND_FROM_EMAIL"],
  SIGNWELL_API_KEY: process.env["SIGNWELL_API_KEY"],
  SIGNWELL_WEBHOOK_ID: process.env["SIGNWELL_WEBHOOK_ID"],
  SIGNWELL_TEST_MODE: process.env["SIGNWELL_TEST_MODE"]
});
