export const FOUNDATION_CAPABILITIES = [
  "identity:read",
  "organization:create",
  "organization:read",
  "organization:switch",
  "invitation:create",
  "invitation:read",
  "membership:read",
  "membership:update",
  "profile:read",
  "profile:update",
  "navigation:access",
  "authorization:manage",
  "dashboard:read",
  "property:create",
  "property:read",
  "property:update",
  "property:archive",
  "property:delete",
  "unit:create",
  "unit:read",
  "unit:update",
  "unit:archive",
  "unit:delete",
  "tenant:create",
  "tenant:read",
  "tenant:update",
  "tenant:archive",
  "tenant:delete",
  "applicant:create",
  "applicant:read",
  "applicant:update",
  "applicant:archive",
  "applicant:delete",
  "document:create",
  "document:read",
  "document:update",
  "document:delete",
  "screening:create",
  "screening:read",
  "screening:update",
  "signature:create",
  "signature:read",
  "signature:update",
  "maintenance:create",
  "maintenance:read",
  "maintenance:update",
  "maintenance:assign",
  "maintenance:archive",
  "maintenance:delete",
  "vendor:create",
  "vendor:read",
  "vendor:update",
  "vendor:archive",
  "vendor:delete",
  "vendor:assign",
  "lease:create",
  "lease:read",
  "lease:update",
  "lease:archive",
  "lease:delete",
  "communication:create",
  "communication:read",
  "communication:update",
  "communication:archive",
  "communication:publish",
  "communication:delete",
  "message:create",
  "message:read",
  "message:update",
  "notification:read",
  "notification:update",
  "financial:create",
  "financial:read",
  "financial:update",
  "financial:archive",
  "financial:delete",
  "ai:read",
  "ai:use",
  "migration:create",
  "migration:read",
  "migration:update",
  "migration:rollback",
  "migration:delete"
] as const;

export type PermissionCapability = (typeof FOUNDATION_CAPABILITIES)[number] | `${string}:${string}`;

export function evaluateCapability(
  grantedCapabilities: readonly string[],
  requiredCapability: PermissionCapability
): boolean {
  if (grantedCapabilities.includes(requiredCapability)) {
    return true;
  }
  const [requiredNamespace] = requiredCapability.split(":");
  return grantedCapabilities.includes(`${requiredNamespace}:*`);
}
