import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import {
  EXECUTIVE_PERSONA_LABELS,
  REPORT_AREA_LABELS,
  type ReportingSnapshot
} from "@mpa/shared";

export async function buildReportingPdf(snapshot: ReportingSnapshot): Promise<{
  bytes: Uint8Array;
  fileName: string;
}> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([612, 792]);
  const margin = 54;
  let y = 738;

  const ensure = (needed: number) => {
    if (y < margin + needed) {
      page = pdf.addPage([612, 792]);
      y = 738;
    }
  };

  const draw = (text: string, size: number, useBold = false, color = rgb(0.08, 0.12, 0.18)) => {
    ensure(size + 10);
    page.drawText(text.slice(0, 100), {
      x: margin,
      y,
      size,
      font: useBold ? bold : font,
      color,
      maxWidth: 612 - margin * 2
    });
    y -= size + 8;
  };

  draw("M.P.A. · Reporting & Analytics", 10, false, rgb(0.25, 0.45, 0.4));
  draw("Executive Intelligence Briefing", 18, true);
  draw(snapshot.organizationName ?? "Organization", 11, false, rgb(0.3, 0.35, 0.4));
  draw(`${EXECUTIVE_PERSONA_LABELS[snapshot.persona]} · ${new Date(snapshot.generatedAt).toLocaleString()}`, 9, false, rgb(0.45, 0.5, 0.55));
  y -= 4;
  page.drawLine({
    start: { x: margin, y },
    end: { x: 612 - margin, y },
    thickness: 1,
    color: rgb(0.85, 0.88, 0.9)
  });
  y -= 16;

  draw(snapshot.attentionQuestion, 12, true);
  y -= 4;

  draw("Insights", 12, true);
  for (const item of snapshot.insights.slice(0, 12)) {
    draw(`• ${item.headline}`, 10, true);
    draw(`  ${item.decision}`, 9, false, rgb(0.3, 0.35, 0.4));
  }

  y -= 6;
  draw("Area summaries", 12, true);
  for (const area of snapshot.areas) {
    draw(REPORT_AREA_LABELS[area.area], 11, true);
    draw(area.summary, 9, false, rgb(0.35, 0.4, 0.45));
    for (const m of area.metrics.slice(0, 6)) {
      draw(`  ${m.label}: ${m.value}`, 9);
    }
    if (area.emptyReason) {
      draw(`  ${area.emptyReason}`, 8, false, rgb(0.45, 0.5, 0.55));
    }
  }

  y -= 8;
  draw("Data honesty", 10, true);
  for (const line of snapshot.dataHonesty) {
    draw(`• ${line}`, 8, false, rgb(0.45, 0.5, 0.55));
  }

  ensure(40);
  y -= 8;
  draw("Generated by My Property Assistant · Reporting & Analytics Center", 8, false, rgb(0.45, 0.5, 0.55));
  draw("Suitable for owners, managers, and operators — print-ready.", 8, false, rgb(0.45, 0.5, 0.55));

  const bytes = await pdf.save();
  const safe = (snapshot.organizationName ?? "organization").replace(/[^a-zA-Z0-9-_ ]+/g, "").trim().replace(/\s+/g, "-");
  return { bytes, fileName: `${safe || "organization"}-executive-briefing.pdf` };
}
