/**
 * SIGN-002 — document templates by workflow type (M.P.A.-owned generation).
 */

import type { SignatureDocumentType } from "./contracts";
import { DEFAULT_LEASE_REQUIRED_FIELDS, DEFAULT_LEASE_TEMPLATE } from "./contracts";

export const DEFAULT_RENEWAL_TEMPLATE = `LEASE RENEWAL AGREEMENT

Property: {{property_name}}
Address: {{property_address}}
Unit: {{unit_number}}

Landlord / Manager: {{org_name}}
Primary Resident: {{primary_name}}
Email: {{primary_email}}

Current / Renewal Start: {{lease_start}}
Renewal End: {{lease_end}}
Monthly Rent: {{rent_amount}}
Security Deposit: {{deposit_amount}}

The parties agree to renew the residential lease on the terms above. Electronic signatures are the legal equivalent of handwritten signatures under applicable ESIGN/UETA laws.

Document generated by M.P.A.
`;

export const DEFAULT_OWNER_AGREEMENT_TEMPLATE = `PROPERTY MANAGEMENT AGREEMENT

Property: {{property_name}}
Address: {{property_address}}

Owner: {{primary_name}}
Owner Email: {{primary_email}}
Management Company: {{org_name}}

The Owner engages the Management Company to manage the Property under the organization's standard management terms. Both parties acknowledge this electronic signature is legally binding under applicable ESIGN/UETA laws.

Document generated by M.P.A.
`;

export const DEFAULT_MOVE_IN_ACK_TEMPLATE = `MOVE-IN ACKNOWLEDGEMENT

Property: {{property_name}}
Address: {{property_address}}
Unit: {{unit_number}}
Resident: {{primary_name}}
Email: {{primary_email}}
Move-In / Lease Start: {{lease_start}}

I acknowledge:
1. I have inspected the unit condition (or will note exceptions separately).
2. I have received keys / access devices as arranged with management.
3. I agree to follow community rules provided by management.

Electronic signature is the legal equivalent of a handwritten signature under applicable ESIGN/UETA laws.

Document generated by M.P.A.
`;

export const DEFAULT_MOVE_OUT_ACK_TEMPLATE = `MOVE-OUT ACKNOWLEDGEMENT

Property: {{property_name}}
Address: {{property_address}}
Unit: {{unit_number}}
Resident: {{primary_name}}
Email: {{primary_email}}
Lease End / Move-Out: {{lease_end}}

I acknowledge:
1. Final inspection findings as communicated by management.
2. Responsibility for documented damages beyond normal wear (if any).
3. Deposit disposition will follow the lease and applicable law.
4. Keys / access devices have been (or will be) returned.

Electronic signature is the legal equivalent of a handwritten signature under applicable ESIGN/UETA laws.

Document generated by M.P.A.
`;

const OWNER_REQUIRED = ["property_name", "property_address", "org_name", "primary_name", "primary_email"];
const MOVE_REQUIRED = [
  "property_name",
  "property_address",
  "unit_number",
  "org_name",
  "primary_name",
  "primary_email"
];

export function resolveDocumentTemplate(documentType: SignatureDocumentType, kind?: string | null): {
  templateBody: string;
  requiredFields: string[];
  title: string;
} {
  if (documentType === "lease_renewal") {
    return {
      templateBody: DEFAULT_RENEWAL_TEMPLATE,
      requiredFields: DEFAULT_LEASE_REQUIRED_FIELDS,
      title: "Lease Renewal Agreement"
    };
  }
  if (documentType === "owner_agreement") {
    return {
      templateBody: DEFAULT_OWNER_AGREEMENT_TEMPLATE,
      requiredFields: OWNER_REQUIRED,
      title: "Owner Management Agreement"
    };
  }
  if (documentType === "move_in_form") {
    return {
      templateBody: DEFAULT_MOVE_IN_ACK_TEMPLATE,
      requiredFields: MOVE_REQUIRED,
      title: "Move-In Acknowledgement"
    };
  }
  if (documentType === "general_pdf" && kind === "move_out_ack") {
    return {
      templateBody: DEFAULT_MOVE_OUT_ACK_TEMPLATE,
      requiredFields: MOVE_REQUIRED,
      title: "Move-Out Acknowledgement"
    };
  }
  return {
    templateBody: DEFAULT_LEASE_TEMPLATE,
    requiredFields: DEFAULT_LEASE_REQUIRED_FIELDS,
    title: "Residential Lease Agreement"
  };
}
